In [1]:
# ---------------------------------------------------------
#                           import libraries
# ---------------------------------------------------------

import pandas as pd 
import numpy as np  
print("labriries imported successfuly")

labriries imported successfuly

In [2]:
# ---------------------------------------------------------------
#                         load data 
# ----------------------------------------------------------------

df=pd.read_csv("rent_2025.csv") 
print("data loaded successfuly")

data loaded successfuly

In [3]:
# -----------------------------------------------------------
#                         first look 
# -----------------------------------------------------------

# show random 20 rows
display(df.sample(20))

,contract_id,contract_start_date,annual_amount,ejari_property_sub_type_en,area_name_en
270823,CNT2128560768,2025-01-27,17000,Office,Um Hurair Second
1230316,CNT2134231492,2025-12-01,288750,Shop,Al Hebiah Fifth
129609,CRT2132926336,2025-10-01,78750,1bed room+Hall,Al Merkadh
709538,CNT2131827937,2025-07-05,16000,Office,Naif
463742,CNT2130472222,2025-04-15,95000,1bed room+Hall,Al Dhagaya
1028033,CNT2133294395,2025-11-03,15000,Office,Al Baraha
984379,CNT2133071637,2025-10-15,2050000,Studio,Al Muteena
422797,CNT2130279163,2025-02-20,82907,Warehouse,Ras Al Khor Industrial Second
522296,CNT2130780771,2025-05-05,15000,Office,Jabal Ali Industrial First
790522,CNT2132219756,2025-05-05,28000,Studio,Al Warsan First
269668,CNT2128549336,2025-01-27,15000,Office,Ras Al Khor Industrial Second
963147,CNT2132978537,2025-09-20,48000,2 bed rooms+hall,Al Baraha
876782,CNT2132597801,2025-09-10,56000,1bed room+Hall,Nadd Hessa
531625,CNT2130829719,2025-04-20,95000,Warehouse,Al Qusais Industrial First
301942,CNT2129253494,2025-01-20,170000,3 bed rooms+hall,Nadd Hessa
1017467,CNT2133236287,2025-10-30,65500,Office,Al Qusais Industrial Third
154563,CRT2133574006,2025-11-20,15000,Studio,Port Saeed
599511,CNT2131160275,2025-05-15,65000,Staff Accommodatoion,Al Karama
341323,CNT2129885273,2025-01-01,68754,Shop,Naif
122280,CRT2132757736,2025-09-15,60000,Shop,Al Baraha

In [4]:
# standardize columns name 
df=df.rename(columns={"ejari_property_sub_type_en":"rooms","area_name_en":"area_name","annual_amount":"annual_rent","master_project_en":"master_project"})

In [5]:
# check duplicate 
print(f"Number of duplicate row : {df.duplicated().sum()}")

# Remove duplicates 
df=df.drop_duplicates() 
print("duplicate rows are removed successfully")

Number of duplicate row : 192178
duplicate rows are removed successfully

In [6]:
# check null values 
null_values=df.isnull().sum() 
total_values=df.shape[0]
print(f"number of null values : \n {(null_values / total_values) * 100 } % ") 

# remove null values ( ~ 0.5%) 
df=df.dropna() 
print('null values are removed successfully')

number of null values :
 contract_id            0.000000
contract_start_date    0.000000
annual_rent            0.000000
rooms                  0.502138
area_name              0.000000
dtype: float64 %
null values are removed successfully

In [7]:
# check rooms unique values
print(df["rooms"].unique())

['Nursery' 'Office' '6 bed rooms+hall' '2 bed rooms+hall'
 '4 bed rooms+hall' 'Showroom' 'Shop' '3 bed rooms+hall' 'Studio' 'Hotel'
 '1bed room+Hall' '8 bed rooms+hall' '5 bed rooms+hall' 'Labor Camp'
 '10 bed rooms+hall' '7 bed rooms+hall' 'Commercial villa'
 'Shop with a mezzanine' 'Restaurant' 'Warehouse' 'Workshop' 'Clinic'
 'Open space' 'Store' 'Parking' '9 bed rooms+hall' 'Room in labor Camp'
 'Storage' 'Kiosk' 'Supermarket' '11 bed rooms+hall' 'Pharmacy' 'GYM'
 'Food court' 'Store cooled' 'Showroom with mezzanine' 'Ladies Saloon'
 'kitchen' 'Factory' 'Farm' 'Coffe shop' 'School' 'Hospital' 'Spa'
 'Open Land' 'Duplex' '15 bed room+hall' 'Penthouse' 'Hat Saloon'
 'Staff Accommodatoion' 'Bank' 'Horse stable' 'Portacabin Rooms'
 'Health club' 'Sign board' 'ATM' 'Room' 'laboratory' 'Garage'
 'Poultry Farm' 'Coffe shop,Fast Food' 'Service Center'
 'Warehouse with a mezzanine' 'Car wash' 'Hall weddings' 'Desk'
 '2 bed rooms+hall+Maids Room' 'College' 'OPEN STORAGE SHED'
 'hotel building' 'Laundry' 'WorkShop with a mezzanine' 'Grocery'
 'Counter Printing' 'Mezzanine' 'Hotel apartments' 'Machine' 'Cinema'
 'Boardroom']

In [8]:
# -----------------------------------------------------------------------------------------------------------
#        
# ------------------------------------------------------------------------------------------------------------

# convert rooms data type into str 
df['rooms']=df['rooms'].astype(str)

# Extract digits and fill missing matches with the original value 
df['rooms']= df['rooms'].str.extract('(\\d+)',expand=False).fillna(df['rooms'])


df['rooms']= df['rooms'].str.strip().str.capitalize()
# note: i coverted rooms to  float becouse NaN are float they cannot convert to int  
# we need only residential data 

display(df.sample(20))

,contract_id,contract_start_date,annual_rent,rooms,area_name
777078,CNT2132146636,2025-11-01,89782,3,Nadd Hessa
812089,CNT2132313827,2025-07-02,50000,Office,Al Wasl
595185,CNT2131134266,2025-06-01,200000,5,Wadi Al Safa 2
159480,CRT2133695603,2025-12-21,118000,3,Madinat Al Mataar
135513,CRT2133069366,2025-10-07,155000,2,Al Merkadh
1220805,CNT2134190329,2026-01-20,88000,2,Al Murqabat
406715,CNT2130207115,2025-03-18,15000,Office,Al Nahda Second
473026,CNT2130517151,2025-04-16,10000,Office,Al Muteena
16359,CRT2128952426,2025-01-01,84000,2,Al Hebiah Fourth
362536,CNT2129997902,2025-03-01,75000,2,Trade Center Second
1060195,CNT2133480740,2025-11-25,87000,Shop,Al-Cornich
430681,CNT2130316476,2025-03-15,72000,1,Al Barsha South Fourth
967280,CNT2132998778,2025-09-01,54000,Room in labor camp,Al Goze Industrial Second
2562,CRT2127192086,2025-01-07,290000,Shop,Al Merkadh
942893,CNT2132898141,2025-10-07,58000,2,Muhaisanah Fourth
675884,CNT2131681052,2025-07-05,160000,3,Wadi Al Safa 5
173541,CRT2134034226,2025-12-02,18000,Studio,Al Baraha
1060903,CNT2133484648,2025-11-18,42500,1,Al Warsan First
444961,CNT2130385611,2025-03-16,100000,Office,Al Thanyah Third
383453,CNT2130102025,2025-03-10,20000,Office,Al Khabeesi

In [9]:
# check null values 
df.isnull().sum()

contract_id            0
contract_start_date    0
annual_rent            0
rooms                  0
area_name              0
dtype: int64

In [10]:
# ------------------------------------------------------------------------------------------------------
#                                        Outliers_Remove 
# ------------------------------------------------------------------------------------------------------

# Define a fuction for outlier 
def remove_outliers_iqr(df, column):
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    
    # Calculate the Interquartile Range
    IQR = Q3 - Q1
    
    # Define bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Filter the DataFrame
    df_filtered = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    
    return df_filtered

# Remove outlier 
df=remove_outliers_iqr(df,'annual_rent')

In [11]:
df['rooms'].value_counts()

rooms
Office            267704
1                 235372
2                 187955
Studio            116155
Shop               54720
                   ...
Service center         1
Grocery                1
Mezzanine              1
Machine                1
Boardroom              1
Name: count, Length: 70, dtype: int64

In [12]:
print(df['area_name'].unique())

['Marsa Dubai' 'Al Barsha Second' 'Al Barsha South Fourth'
 'Al Mizhar First' 'Business Bay' 'Hatta' 'Al Hebiah First'
 'Um Suqaim Third' 'Al Suq Al Kabeer' 'Al Thanayah Fourth'
 'Al Thanyah Third' 'Al Buteen' 'Mirdif' 'Al Barshaa South First'
 'Wadi Al Safa 2' 'Palm Jumeirah' 'AL QUSAIS' 'Al Satwa' 'Al Ras'
 'Al Yelayiss 2' 'Nadd Hessa' 'Al Twar Fourth' 'Al Khairan First'
 'Al Thanyah Fifth' 'Um Suqaim First' 'Al Merkadh' 'Madinat Hind 4'
 'Ras Al Khor Industrial Third' 'Naif' 'Burj Khalifa' 'Al Saffa Second'
 'Al Hebiah Fourth' 'Hor Al Anz East' 'Jabal Ali First' 'Wadi Al Safa 6'
 'Wadi Al Safa 3' 'Wadi Al Safa 5' 'Jumeirah First' "Me'Aisem First"
 'Eyal Nasser' 'Al Manara' 'Muhaisanah Third' 'Trade Center First'
 'Madinat Al Mataar' 'Al Hebiah Third' 'Hor Al Anz' 'Al Mizhar Second'
 'Zaabeel Second' 'Nad Al Hamar' 'Al Warsan First' 'Al Barsha Third'
 'Nad Al Shiba Third' 'Al Rashidiya' 'Al Hebiah Sixth' 'Um Ramool'
 'Hadaeq Sheikh Mohammed Bin Rashid' 'Al Khawaneej Second' 'Al Jadaf'
 'Al Hebiah Fifth' 'Al Warqa Second' 'Al Thanyah First' 'Al Hamriya'
 'Al Rega' 'Al Waheda' 'Al Goze First' 'Warsan Fourth' 'Al Nahda Second'
 'Um Suqaim Second' 'Al Warqa Fourth' 'Dubai Investment Park Second'
 'Abu Hail' 'Ras Al Khor Industrial Second' 'Oud Metha' 'Al Bada'
 'Ras Al Khor Industrial First' 'Al Qusais Industrial Second' 'Al Karama'
 'Al Aweer First' 'Muhaisanah Second' 'Al Yelayiss 1'
 'Al Barsha South Fifth' 'Al Warqa First' 'Al Dhagaya' 'Wadi Al Safa 7'
 'Ghadeer Al tair' 'Al Baraha' 'Al Maha' 'Rega Al Buteen' 'Saih Shuaib 4'
 'Al Mararr' 'Al Hebiah Second' 'Port Saeed' 'Mankhool'
 'Al Barshaa South Third' 'Al Goze Fourth' 'Al Qusais Industrial First'
 'Dubai Investment Park First' 'Al Nahda First' 'Al Sabkha'
 'Al Twar First' 'Al Qusais Industrial Third' 'Al Jafliya' 'Al Raffa'
 'Al Warsan Third' 'Jabal Ali Industrial Second' 'Al Barsha First'
 'Al Kheeran' 'Nad Al Shiba First' 'Muhaisanah First' 'Al Muteena'
 'Al Mamzer' 'Al Barshaa South Second' 'Al Kifaf' 'Al Garhoud'
 'Al Murqabat' 'Al Wasl' 'Al Goze Industrial Fourth' 'Saih Shuaib 2'
 'Al Warqa Third' 'Al Lusaily' 'Muhaisanah Fourth' 'Um Al Sheif'
 'Saih Shuaib 3' 'Al Safouh Second' 'Madinat Dubai Almelaheyah' 'Al Eyas'
 'Trade Center Second' 'Jabal Ali Industrial First' 'Al Khawaneej First'
 'Al Yufrah 1' 'Al Twar Second' 'Al Twar Third' 'Al Goze Third'
 'Al Goze Industrial Second' 'Al Khabeesi' 'Lehbab Second' 'Margham'
 'Jumeirah Third' 'Al Ttay' 'Al Saffa First' 'Al Marmoom'
 'Al Goze Industrial Third' 'Saih Shuaib 1' 'Hessyan First'
 'Um Hurair Second' 'Al Hudaiba' 'Al Safouh First' 'Al Mizhar Third'
 'Lehbab First' 'Al Qusais Industrial Fourth' 'Al Warsan Second'
 'AL Athbah' 'Al Rowaiyah Third' 'Nad Al Shiba Fourth' 'Um Hurair First'
 'Jumeirah Second' 'Shandagha' 'Madinat Hind 3' 'Zaabeel First'
 'AL TWAR FIFTH' 'Al Aweer Second' 'Al Hamriya Port' 'Nad Al Shiba'
 'Al Qoaz' 'AL MIZHAR FOURTH' 'Muragab' 'Dubai International Airport'
 'Nad Shamma' 'Island 2' 'Mushrif' 'Wadi Al Amardi' 'Wadi Al Safa 4'
 'Nad Al Shiba Second' 'Al-Cornich' 'Umm Addamin' 'Al Rowaiyah First'
 'Bur Dubai' 'Nazwah' 'Saih Aldahal' 'Palm Deira' 'Grayteesah'
 'Al Rowaiyah Second' 'Al Goze Industrial First' 'Jabal Ali Second'
 'Bukadra' 'Cornich Deira' 'Al Qusais Industrial Fifth' 'Madinat Hind 1'
 'OUD AL MUTEENA' 'Mena Jabal Ali' 'Al Layan1' 'Jabal Ali'
 'Madinat Hind 2' 'Al Thanyah Second' 'Al Yufrah 4']

In [13]:
# Cleaning Dictionary
area_corrections = {
    # Fix Spelling/Transliteration
    'Al Barshaa South First': 'Al Barsha South First',
    'Al Barshaa South Second': 'Al Barsha South Second',
    'Al Barshaa South Third': 'Al Barsha South Third',
    'Al Thanayah Fourth': 'Al Thanyah Fourth',
    'Al Qoaz': 'Al Goze',
    'Nadd Hessa':'Nad Hessa',

    # Fix Caps (Case Sensitivity)
    'AL QUSAIS': 'Al Qusais',
    'AL TWAR FIFTH': 'Al Twar Fifth',
    'AL MIZHAR FOURTH': 'Al Mizhar Fourth',
    'OUD AL MUTEENA': 'Oud Al Muteena'
}

# replace area_name 
df['area_name'] = df['area_name'].replace(area_corrections)

In [14]:
# --------------------------------------------------------------------------------
#                                Export cleaned_rent 
# -------------------------------------------------------------------------------

df.to_csv("cleaned_rent.csv",index=False)

In [15]:
df.head()

,contract_id,contract_start_date,annual_rent,rooms,area_name
8,CRT2066977807,2025-01-01,70000,2,Marsa Dubai
9,CRT2075310386,2025-10-01,100000,4,Al Barsha Second
12,CRT2085894456,2025-09-16,60650,Office,Al Barsha South Fourth
13,CRT2094378796,2025-01-01,70000,Shop,Al Mizhar First
16,CRT2103611966,2025-02-15,89250,Office,Business Bay

In [16]:
df.shape

(968343, 5)

In [17]:
df.sample(10000).to_csv("cleaned_rent_sample.csv",index=False)