In [1]:
# --------------------------------------------------------------------------------
#                                          import libraries                       
# --------------------------------------------------------------------------------

import numpy as np 
import pandas as pd 
print("libraries imported successfully")

libraries imported successfully

In [2]:
# -----------------------------------------------------------------------------------
#                                             load data                              
# -----------------------------------------------------------------------------------

df=pd.read_csv("transactions_2024_to_2026.csv") 
print("data loaded successfully")

data loaded successfully

In [3]:
# -------------------------------------------------------------------------------------
#                                             first look                               
# -------------------------------------------------------------------------------------

# show 1st five rows
display(df.tail(50))

# show total number of entries and columns,each column's data type ,non_null value's counts,memory_usage
display(df.info())

,transaction_id,trans_group,procedure_name,instance_date,property_type,property_sub_type,property_usage,reg_type,area_name,building_name,project_name,nearest_landmark,nearest_metro,nearest_mall,rooms,has_parking,procedure_area,actual_worth,meter_sale_price
403100,1-102-2026-2515,Sales,Sell - Pre registration,2026-01-09,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,Palatium Residences,Palatium Residences,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1 B/R,1,81.89,1100368.0,13437.15
403101,1-102-2026-2488,Sales,Sell - Pre registration,2026-01-09,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,Palatium Residences,Palatium Residences,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1 B/R,1,120.08,1162870.0,9684.13
403102,1-102-2024-97783,Sales,Sell - Pre registration,2024-11-20,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,Palatium Residences,Palatium Residences,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,Studio,1,37.67,630634.0,16741.01
403103,1-102-2024-94489,Sales,Sell - Pre registration,2024-11-08,Villa,Villa,Residential,Off-Plan Properties,Al Yufrah 1,NaN,The Valley - Velora 2,NaN,NaN,NaN,4 B/R,0,274.80,3407888.0,12401.34
403104,1-102-2024-106287,Sales,Sell - Pre registration,2024-12-19,Villa,Villa,Residential,Off-Plan Properties,Wadi Al Safa 7,NaN,Reportage Village 1,NaN,NaN,NaN,2 B/R,0,88.00,1471958.0,16726.80
403105,1-41-2025-14827,Sales,Delayed Sell,2025-05-15,Land,NaN,Commercial,Existing Properties,Madinat Hind 4,NaN,DAMAC HILLS (2) - VIOLET 4,NaN,NaN,NaN,NaN,0,112.24,2044760.0,18217.75
403106,1-41-2025-5527,Sales,Delayed Sell,2025-02-05,Land,NaN,Commercial,Existing Properties,Madinat Hind 4,NaN,DAMAC HILLS (2) - VIOLET 3,NaN,NaN,NaN,NaN,0,112.24,2001000.0,17827.87
403107,1-102-2025-29226,Sales,Sell - Pre registration,2025-04-10,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,Ashton Park Residences - The Second,Ashton Park Residences The Second,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1 B/R,1,65.82,1079851.0,16406.12
403108,1-102-2025-10295,Sales,Sell - Pre registration,2025-02-10,Villa,Villa,Residential,Off-Plan Properties,Madinat Al Mataar,NaN,Greenridge,NaN,NaN,NaN,3 B/R,0,188.48,3304888.0,17534.42
403109,1-102-2025-45464,Sales,Sell - Pre registration,2025-05-28,Unit,Flat,Residential,Off-Plan Properties,Al Satwa,EVERGRIN HOUSE,EVERGRIN HOUSE,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,36.84,968860.0,26299.13
403110,1-102-2025-22553,Sales,Sell - Pre registration,2025-03-19,Unit,Flat,Residential,Off-Plan Properties,Al Satwa,EVERGRIN HOUSE,EVERGRIN HOUSE,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,47.69,1114340.0,23366.32
403111,1-41-2025-16256,Sales,Delayed Sell,2025-05-27,Land,NaN,Residential,Existing Properties,Al Yelayiss 1,NaN,DAMAC SUN CITY,NaN,NaN,NaN,NaN,0,219.60,3954000.0,18005.46
403112,1-41-2024-24172,Sales,Delayed Sell,2024-12-12,Land,NaN,Residential,Existing Properties,Al Yelayiss 1,NaN,DAMAC SUN CITY,NaN,NaN,NaN,NaN,0,244.35,3809000.0,15588.30
403113,1-41-2025-6851,Sales,Delayed Sell,2025-02-18,Land,NaN,Other,Existing Properties,Al Yelayiss 1,NaN,DAMAC ISLANDS - MALDIVES 3,NaN,NaN,NaN,NaN,0,143.91,2506000.0,17413.66
403114,1-41-2025-15219,Sales,Delayed Sell,2025-05-20,Land,NaN,Other,Existing Properties,Al Yelayiss 1,NaN,DAMAC ISLANDS - MALDIVES 5,NaN,NaN,NaN,NaN,0,226.53,3200000.0,14126.16
403115,1-41-2025-25039,Sales,Delayed Sell,2025-09-08,Land,NaN,Commercial,Existing Properties,Me'Aisem Second,NaN,The Oasis - Palace Villas - Ostra,NaN,NaN,NaN,NaN,0,864.63,15437888.0,17854.91
403116,1-102-2025-64762,Sales,Sell - Pre registration,2025-07-21,Unit,Flat,Residential,Off-Plan Properties,Jabal Ali First,Trussardi Residences 2 - TOWER A,Trussardi Residences 2,NaN,NaN,NaN,Studio,1,37.39,810212.0,21669.22
403117,1-102-2025-125977,Sales,Sell - Pre registration,2025-12-10,Unit,Flat,Residential,Off-Plan Properties,Jabal Ali First,Trussardi Residences 2 - TOWER B,Trussardi Residences 2,NaN,NaN,NaN,Studio,1,39.16,947758.0,24202.20
403118,1-41-2025-13463,Sales,Delayed Sell,2025-05-02,Land,NaN,Commercial,Existing Properties,Me'Aisem Second,NaN,The Oasis - Address Villas - Tierra,NaN,NaN,NaN,NaN,0,852.83,15103888.0,17710.32
403119,1-41-2025-15961,Sales,Delayed Sell,2025-05-26,Land,NaN,Industrial,Existing Properties,Dubai Investment Park Second,NaN,Grand Polo - Chevalia Fields,NaN,NaN,NaN,NaN,0,527.74,9228888.0,17487.57
403120,1-41-2025-16738,Sales,Delayed Sell,2025-05-29,Land,NaN,Industrial,Existing Properties,Dubai Investment Park Second,NaN,Grand Polo - Montura 2,NaN,NaN,NaN,NaN,0,432.00,5566888.0,12886.31
403121,1-102-2025-116618,Sales,Sell - Pre registration,2025-11-17,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER A,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,47.59,1392999.0,29270.83
403122,1-102-2025-127716,Sales,Sell - Pre registration,2025-12-15,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER A,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1 B/R,1,74.39,2278999.0,30635.82
403123,1-102-2025-89521,Sales,Sell - Pre registration,2025-09-17,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER A,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,44.08,1201999.0,27268.58
403124,1-102-2025-92250,Sales,Sell - Pre registration,2025-09-22,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER A,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.35,1202999.0,30571.77
403125,1-102-2025-78638,Sales,Sell - Pre registration,2025-08-21,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER A,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,43.60,1204999.0,27637.59
403126,1-102-2025-77370,Sales,Sell - Pre registration,2025-08-19,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER B,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,2 B/R,1,97.33,2959999.0,30411.99
403127,1-102-2025-55842,Sales,Sell - Pre registration,2025-06-26,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER B,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1 B/R,1,81.37,2293999.0,28192.20
403128,1-102-2025-52165,Sales,Sell - Pre registration,2025-06-18,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER B,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.59,1213999.0,30664.28
403129,1-102-2025-47843,Sales,Sell - Pre registration,2025-06-04,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER C,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,40.40,1049999.0,25990.07
403130,1-102-2025-64847,Sales,Sell - Pre registration,2025-07-21,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER C,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.35,1166999.0,29656.90
403131,1-102-2025-74073,Sales,Sell - Pre registration,2025-08-12,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER C,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,41.58,1203999.0,28956.20
403132,1-102-2025-88317,Sales,Sell - Pre registration,2025-09-15,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER C,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,44.97,1253999.0,27885.23
403133,1-102-2025-95679,Sales,Sell - Pre registration,2025-09-29,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER D,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,45.14,1238999.0,27447.92
403134,1-102-2025-44857,Sales,Sell - Pre registration,2025-05-26,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER D,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,43.60,1192999.0,27362.36
403135,1-102-2025-49758,Sales,Sell - Pre registration,2025-06-11,Unit,Flat,Residential,Off-Plan Properties,Business Bay,Binghatti Aquarise - TOWER D,Binghatti Aquarise,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1 B/R,1,66.26,2054999.0,31014.17
403136,1-102-2025-108731,Sales,Sell - Pre registration,2025-10-29,Villa,Villa,Residential,Off-Plan Properties,Dubai Investment Park Second,NaN,DAMAC RIVERSIDE - OLIVE,NaN,NaN,NaN,4 B/R,0,144.00,2703000.0,18770.83
403137,1-102-2025-77597,Sales,Sell - Pre registration,2025-08-20,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,AURESTA TOWER,AURESTA TOWER,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.91,479771.0,15521.55
403138,1-102-2025-116742,Sales,Sell - Pre registration,2025-11-17,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,AURESTA TOWER,AURESTA TOWER,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.52,740744.0,24270.77
403139,1-102-2025-75031,Sales,Sell - Pre registration,2025-08-14,Unit,Flat,Residential,Off-Plan Properties,Al Barsha South Fourth,AURESTA TOWER,AURESTA TOWER,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.91,495681.0,16036.29
403140,1-102-2025-91909,Sales,Sell - Pre registration,2025-09-22,Villa,Villa,Residential,Off-Plan Properties,Madinat Al Mataar,NaN,Hayat 3,NaN,NaN,NaN,5 B/R,0,377.92,5137308.0,13593.64
403141,1-102-2025-98637,Sales,Sell - Pre registration,2025-10-06,Unit,Flat,Residential,Off-Plan Properties,Nadd Hessa,BELLE VIE BY ZIMAYA,BELLE VIE BY ZIMAYA,NaN,NaN,NaN,Studio,1,39.69,716151.0,18043.61
403142,1-102-2025-99881,Sales,Sell - Pre registration,2025-10-07,Unit,Flat,Residential,Off-Plan Properties,Nadd Hessa,BELLE VIE BY ZIMAYA,BELLE VIE BY ZIMAYA,NaN,NaN,NaN,2 B/R,1,119.85,1643500.0,13712.97
403143,1-102-2025-114132,Sales,Sell - Pre registration,2025-11-11,Villa,Villa,Residential,Off-Plan Properties,Al Yufrah 1,NaN,The Valley - Vindera,NaN,NaN,NaN,4 B/R,0,260.40,4217888.0,16197.73
403144,1-102-2025-134864,Sales,Sell - Pre registration,2025-12-29,Unit,Flat,Residential,Off-Plan Properties,Madinat Al Mataar,Golf Hills,Golf Hills,NaN,NaN,NaN,1 B/R,1,63.19,1079888.0,17089.54
403145,1-102-2026-959,Sales,Sell - Pre registration,2026-01-06,Unit,Flat,Residential,Off-Plan Properties,Palm Deira,ELLINGTON SANDS I - TOWER B,ELLINGTON SANDS I,NaN,NaN,NaN,1 B/R,1,74.70,2269828.0,30385.92
403146,1-102-2025-125823,Sales,Sell - Pre registration,2025-12-10,Unit,Flat,Residential,Off-Plan Properties,Palm Deira,ELLINGTON SANDS I - TOWER B,ELLINGTON SANDS I,NaN,NaN,NaN,2 B/R,1,129.20,3901828.0,30199.91
403147,1-102-2025-129954,Sales,Sell - Pre registration,2025-12-18,Villa,Villa,Residential,Off-Plan Properties,Dubai Investment Park Second,NaN,Grand Polo - Equiterra,NaN,NaN,NaN,3 B/R,0,148.78,3614888.0,24296.87
403148,1-102-2025-129644,Sales,Sell - Pre registration,2025-12-18,Villa,Villa,Residential,Off-Plan Properties,Dubai Investment Park Second,NaN,Grand Polo - Equiterra,NaN,NaN,NaN,4 B/R,0,286.84,4752888.0,16569.82
403149,1-41-2025-30441,Sales,Delayed Sell,2025-12-03,Land,NaN,Commercial,Existing Properties,Madinat Hind 4,NaN,Sold Without Project for Front Line Investment...,NaN,NaN,NaN,NaN,0,174.79,685000.0,3918.99

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403150 entries, 0 to 403149
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   transaction_id     403150 non-null  object
 1   trans_group        403150 non-null  object
 2   procedure_name     403150 non-null  object
 3   instance_date      403150 non-null  object
 4   property_type      403150 non-null  object
 5   property_sub_type  358582 non-null  object
 6   property_usage     403150 non-null  object
 7   reg_type           403150 non-null  object
 8   area_name          403150 non-null  object
 9   building_name      327116 non-null  object
 10  project_name       367231 non-null  object
 11  nearest_landmark   260690 non-null  object
 12  nearest_metro      218952 non-null  object
 13  nearest_mall       214529 non-null  object
 14  rooms              353565 non-null  object
 15  has_parking        403150 non-null  int64
 16  procedure_area     403150 non-null  float64
 17  actual_worth       403150 non-null  float64
 18  meter_sale_price   403150 non-null  float64
dtypes: float64(3), int64(1), object(15)
memory usage: 58.4+ MB

None

In [4]:
# we have to analyze "Sell" ,"Sell-pre registration" and  "Residential" data 
# Extract the data 

df=df.query ("procedure_name == ['Sell','Sell - Pre registration'] and property_usage == 'Residential'")

In [5]:
# Change instance_date data_type to datetime 
df["instance_date"]=pd.to_datetime(df["instance_date"],errors="coerce") 
print("data type changed successfuly")

data type changed successfuly

In [6]:
# Check duplicates 
display(df.duplicated().sum())

np.int64(0)

In [7]:
# Check nulls 
null_values=df.isnull().sum()
total_values=df.shape[0]
print(f"{(null_values / total_values) * 100} %")

transaction_id        0.000000
trans_group           0.000000
procedure_name        0.000000
instance_date         0.000000
property_type         0.000000
property_sub_type     2.934152
property_usage        0.000000
reg_type              0.000000
area_name             0.000000
building_name        11.517138
project_name          8.305471
nearest_landmark     32.185892
nearest_metro        42.575137
nearest_mall         43.766513
rooms                 2.995822
has_parking           0.000000
procedure_area        0.000000
actual_worth          0.000000
meter_sale_price      0.000000
dtype: float64 %

In [8]:
# --------------------------------------------------------------------------------------------------
#                                                  handle null values 
# ----------------------------------------------------------------------------------------------------

df["property_sub_type"]=df["property_sub_type"].fillna("unknown") 

# Impute missing values using forward fill (ffill)
# Reason: The data follows a grouped structure where missing entries 
# imply a continuation of the preceding valid record (ditto marks).
df["building_name"]=df['building_name'].ffill(axis=0)
df['project_name']=df['project_name'].ffill(axis=0)
df['nearest_landmark']=df['nearest_landmark'].ffill(axis=0)
df['nearest_mall']=df['nearest_mall'].ffill(axis=0)
df['nearest_metro']=df['nearest_metro'].ffill(axis=0) 

# drop rooms NAN (~3%)
df=df.dropna(subset=["rooms"])

In [9]:
df['rooms'].value_counts(dropna=False)

rooms
1 B/R          131293
2 B/R           75391
Studio          68317
3 B/R           29649
4 B/R           14076
5 B/R            1849
6 B/R             161
PENTHOUSE          97
7 B/R              24
Single Room        21
Shop                4
9 B/R               2
Name: count, dtype: int64

In [10]:
# ensure the column is string type first 
df['rooms']=df['rooms'].astype(str)

# remove "B/R" 
df['rooms']=df['rooms'].str.replace("B/R",'',regex=True).str.strip()


# Single --> '1' 
df['rooms']=df['rooms'].str.replace('Single Room' ,'1',regex=True).str.strip()


# strip whitespace one last time 
df['rooms']=df['rooms'].str.strip().str.capitalize()

print(df['rooms'].value_counts())

rooms
1            131314
2             75391
Studio        68317
3             29649
4             14076
5              1849
6               161
Penthouse        97
7                24
Shop              4
9                 2
Name: count, dtype: int64

In [11]:
print(df.isnull().sum())

transaction_id       0
trans_group          0
procedure_name       0
instance_date        0
property_type        0
property_sub_type    0
property_usage       0
reg_type             0
area_name            0
building_name        0
project_name         0
nearest_landmark     0
nearest_metro        0
nearest_mall         0
rooms                0
has_parking          0
procedure_area       0
actual_worth         0
meter_sale_price     0
dtype: int64

In [12]:
# ------------------------------------------------------------------------------------------------------
#                                        Outliers_Remove 
# ------------------------------------------------------------------------------------------------------

# Define a fuction for outlier 
def remove_outliers_iqr(df, column):
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    
    # Calculate the Interquartile Range
    IQR = Q3 - Q1
    
    # Define bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Filter the DataFrame
    df_filtered = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    
    return df_filtered

# Remove outlier 
df=remove_outliers_iqr(df,'procedure_area')
df=remove_outliers_iqr(df,'actual_worth')
df=remove_outliers_iqr(df,'meter_sale_price')

print(f'shape:{df.shape}')

shape:(283993, 19)

In [13]:
# procedure_area ,actual_worth and meter_sale_price must be positive 
# check for negitive values 
negitive_values=df.query("meter_sale_price <= 0 or actual_worth <= 0 or procedure_area <= 0") 
print(negitive_values.value_counts())

Series([], Name: count, dtype: int64)

In [14]:
# Check area unique_name
df['area_name'].unique()

array(['Burj Khalifa', 'Al Safouh Second', 'Al Thanyah Fifth',
       'Marsa Dubai', 'Al Thanyah Third', 'Palm Jumeirah',
       'Al Warsan First', 'Al Barsha First', 'Al Barshaa South Second',
       'Al Hebiah Fourth', 'Al Thanayah Fourth', 'Palm Deira', 'Al Jadaf',
       'Al Qusais Industrial Fourth', 'Al Barshaa South Third',
       'Madinat Dubai Almelaheyah', 'Al Barsha South Fourth',
       'Al Barsha South Fifth', 'Al Thanyah First', 'Al Hebiah First',
       'Bukadra', 'Saih Shuaib 2', "Me'Aisem First",
       'Jabal Ali Industrial Second', 'Jabal Ali', 'Warsan Fourth',
       'Jabal Ali First', 'Business Bay', 'Nad Al Shiba First',
       'Al Goze Fourth', 'Zaabeel Second', 'Al Merkadh',
       'Al Hebiah Second', 'Hadaeq Sheikh Mohammed Bin Rashid', 'Al Wasl',
       'Muhaisanah First', 'Al Khairan First', 'Al Satwa',
       'Madinat Al Mataar', 'Al Kifaf', 'Jumeirah First',
       'Dubai Investment Park Second', 'Wadi Al Safa 5', 'Wadi Al Safa 2',
       'Al Yelayiss 2', 'Um Suqaim Third', 'Wadi Al Safa 3',
       'Wadi Al Safa 7', 'Al Yufrah 1', 'Wadi Al Safa 4', 'Al Yelayiss 1',
       'Al Hebiah Third', 'Madinat Hind 4', 'Nadd Hessa',
       'Al Hebiah Sixth', 'Al Hebiah Fifth', 'Al Safouh First',
       'Ras Al Khor Industrial First', 'Mirdif', 'Trade Center First',
       'Zaabeel First', 'Rega Al Buteen', 'Hessyan First',
       'Wadi Al Safa 6', 'Nad Al Hamar', 'Al Kheeran', 'Palm Jabal Ali',
       'Nad Al Shiba', 'Al Qusais Industrial Fifth', 'Um Hurair Second',
       'Trade Center Second', 'Jumeirah Second'], dtype=object)

In [15]:
# ----------------------------------------------------------------------
#                                Standardize Area Names
# ----------------------------------------------------------------------

# Remove  the whitespace 

df['area_name']=df['area_name'].str.strip()

#  Define the Cleaning Map (Dictionary)
# This maps the "Wrong/Inconsistent Name" to the "Correct Standard Name"
cleaning_map = {
    # Fix "Barshaa" (extra 'a')
    'Al Barshaa South First': 'Al Barsha South First',
    'Al Barshaa South Second': 'Al Barsha South Second',
    'Al Barshaa South Third' : 'Al Barsha South Third',
    
    # Fix "Thanayah" (extra 'a')
    'Al Thanayah Fourth': 'Al Thanyah Fourth',
    
    # Fix "Kheeran" (This is the only merge: it is the same as Khairan)
    'Al Kheeran': 'Al Khairan First',
    
    # Standardize "Nadd" to "Nad"
    'Nadd Hessa': 'Nad Hessa'
}

#  Apply the fix
# We use .replace() which looks for exact matches of the keys and replaces them
df['area_name'] = df['area_name'].replace(cleaning_map)

In [16]:
# -----------------------------------------------------------------------
#                           Standardize reg_type 
# -----------------------------------------------------------------------

df["reg_type"]=df["reg_type"] = df["reg_type"].map({
    "Off-Plan Properties": "Off-Plan",
    "Existing Properties": "Existing"
}).fillna(df["reg_type"]) # fillna keeps original values if not found in map

In [17]:
# ------------------------------------------------------------------------------------
#                                       Feature_Engeering                            
# ------------------------------------------------------------------------------------

# convert area meter to feet
df["area_sqft"] = (df["procedure_area"]) * 10.764

# price per_sequare_feet
df["Price_Per_SqFt"] = df["actual_worth"] / df["area_sqft"]

In [18]:
# last check 
df.tail(50)

,transaction_id,trans_group,procedure_name,instance_date,property_type,property_sub_type,property_usage,reg_type,area_name,building_name,...,nearest_landmark,nearest_metro,nearest_mall,rooms,has_parking,procedure_area,actual_worth,meter_sale_price,area_sqft,Price_Per_SqFt
403085,1-102-2025-70366,Sales,Sell - Pre registration,2025-08-04,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 1,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,2,1,145.83,3129411.0,21459.31,1569.71412,1993.618430
403086,1-102-2024-99849,Sales,Sell - Pre registration,2024-11-27,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 1,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1,1,114.64,1200000.0,10467.55,1233.98496,972.459178
403087,1-102-2025-112120,Sales,Sell - Pre registration,2025-11-06,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,42.99,1032293.0,24012.40,462.74436,2230.806227
403088,1-102-2024-70738,Sales,Sell - Pre registration,2024-09-12,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1,1,89.91,1199999.0,13346.67,967.79124,1239.935794
403089,1-102-2024-70232,Sales,Sell - Pre registration,2024-09-11,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,51.71,790000.0,15277.51,556.60644,1419.315235
403090,1-102-2024-86284,Sales,Sell - Pre registration,2024-10-16,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1,1,82.73,1175000.0,14202.83,890.50572,1319.474961
403091,1-102-2024-91506,Sales,Sell - Pre registration,2024-10-29,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,43.58,800000.0,18357.04,469.09512,1705.411048
403092,1-102-2025-3567,Sales,Sell - Pre registration,2025-01-20,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,41.45,600000.0,14475.27,446.16780,1344.785527
403093,1-102-2024-108991,Sales,Sell - Pre registration,2024-12-27,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,2,1,166.28,1400000.0,8419.53,1789.83792,782.193731
403094,1-102-2025-35449,Sales,Sell - Pre registration,2025-04-28,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,46.18,780000.0,16890.43,497.08152,1569.159119
403095,1-102-2024-65140,Sales,Sell - Pre registration,2024-08-27,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1,1,79.64,1210000.0,15193.37,857.24496,1411.498529
403096,1-102-2025-133894,Sales,Sell - Pre registration,2025-12-29,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,41.45,1044705.0,25203.98,446.16780,2341.506940
403097,1-102-2024-65425,Sales,Sell - Pre registration,2024-08-27,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,1,1,76.79,1200000.0,15627.03,826.56756,1451.786954
403098,1-102-2025-30199,Sales,Sell - Pre registration,2025-04-14,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,2,1,145.80,2000000.0,13717.42,1569.39120,1274.379517
403099,1-102-2024-109730,Sales,Sell - Pre registration,2024-12-30,Unit,Flat,Residential,Off-Plan,Al Barsha South Second,Binghatti Hills - 2,...,Motor City,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Studio,1,41.57,860000.0,20688.00,447.45948,1921.961738
403100,1-102-2026-2515,Sales,Sell - Pre registration,2026-01-09,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,Palatium Residences,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1,1,81.89,1100368.0,13437.15,881.46396,1248.341452
403101,1-102-2026-2488,Sales,Sell - Pre registration,2026-01-09,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,Palatium Residences,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1,1,120.08,1162870.0,9684.13,1292.54112,899.677374
403102,1-102-2024-97783,Sales,Sell - Pre registration,2024-11-20,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,Palatium Residences,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,Studio,1,37.67,630634.0,16741.01,405.47988,1555.278156
403104,1-102-2024-106287,Sales,Sell - Pre registration,2024-12-19,Villa,Villa,Residential,Off-Plan,Wadi Al Safa 7,Palatium Residences,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,2,0,88.00,1471958.0,16726.80,947.23200,1553.957214
403107,1-102-2025-29226,Sales,Sell - Pre registration,2025-04-10,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,Ashton Park Residences - The Second,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,1,1,65.82,1079851.0,16406.12,708.48648,1524.165994
403108,1-102-2025-10295,Sales,Sell - Pre registration,2025-02-10,Villa,Villa,Residential,Off-Plan,Madinat Al Mataar,Ashton Park Residences - The Second,...,Sports City Swimming Academy,Nakheel Metro Station,Marina Mall,3,0,188.48,3304888.0,17534.42,2028.79872,1628.987621
403109,1-102-2025-45464,Sales,Sell - Pre registration,2025-05-28,Unit,Flat,Residential,Off-Plan,Al Satwa,EVERGRIN HOUSE,...,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,36.84,968860.0,26299.13,396.54576,2443.248920
403110,1-102-2025-22553,Sales,Sell - Pre registration,2025-03-19,Unit,Flat,Residential,Off-Plan,Al Satwa,EVERGRIN HOUSE,...,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,47.69,1114340.0,23366.32,513.33516,2170.784483
403116,1-102-2025-64762,Sales,Sell - Pre registration,2025-07-21,Unit,Flat,Residential,Off-Plan,Jabal Ali First,Trussardi Residences 2 - TOWER A,...,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,37.39,810212.0,21669.22,402.46596,2013.119321
403117,1-102-2025-125977,Sales,Sell - Pre registration,2025-12-10,Unit,Flat,Residential,Off-Plan,Jabal Ali First,Trussardi Residences 2 - TOWER B,...,Burj Khalifa,Trade Centre Metro Station,Dubai Mall,Studio,1,39.16,947758.0,24202.20,421.51824,2248.438881
403121,1-102-2025-116618,Sales,Sell - Pre registration,2025-11-17,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER A,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,47.59,1392999.0,29270.83,512.25876,2719.326850
403122,1-102-2025-127716,Sales,Sell - Pre registration,2025-12-15,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER A,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1,1,74.39,2278999.0,30635.82,800.73396,2846.137561
403123,1-102-2025-89521,Sales,Sell - Pre registration,2025-09-17,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER A,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,44.08,1201999.0,27268.58,474.47712,2533.312881
403124,1-102-2025-92250,Sales,Sell - Pre registration,2025-09-22,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER A,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.35,1202999.0,30571.77,423.56340,2840.186381
403125,1-102-2025-78638,Sales,Sell - Pre registration,2025-08-21,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER A,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,43.60,1204999.0,27637.59,469.31040,2567.594922
403126,1-102-2025-77370,Sales,Sell - Pre registration,2025-08-19,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER B,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,2,1,97.33,2959999.0,30411.99,1047.66012,2825.342822
403127,1-102-2025-55842,Sales,Sell - Pre registration,2025-06-26,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER B,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1,1,81.37,2293999.0,28192.20,875.86668,2619.118928
403128,1-102-2025-52165,Sales,Sell - Pre registration,2025-06-18,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER B,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.59,1213999.0,30664.28,426.14676,2848.781486
403129,1-102-2025-47843,Sales,Sell - Pre registration,2025-06-04,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER C,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,40.40,1049999.0,25990.07,434.86560,2414.536813
403130,1-102-2025-64847,Sales,Sell - Pre registration,2025-07-21,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER C,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,39.35,1166999.0,29656.90,423.56340,2755.193201
403131,1-102-2025-74073,Sales,Sell - Pre registration,2025-08-12,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER C,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,41.58,1203999.0,28956.20,447.56712,2690.097074
403132,1-102-2025-88317,Sales,Sell - Pre registration,2025-09-15,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER C,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,44.97,1253999.0,27885.23,484.05708,2590.601505
403133,1-102-2025-95679,Sales,Sell - Pre registration,2025-09-29,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER D,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,45.14,1238999.0,27447.92,485.88696,2549.973763
403134,1-102-2025-44857,Sales,Sell - Pre registration,2025-05-26,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER D,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,Studio,1,43.60,1192999.0,27362.36,469.31040,2542.025491
403135,1-102-2025-49758,Sales,Sell - Pre registration,2025-06-11,Unit,Flat,Residential,Off-Plan,Business Bay,Binghatti Aquarise - TOWER D,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,1,1,66.26,2054999.0,31014.17,713.22264,2881.286831
403136,1-102-2025-108731,Sales,Sell - Pre registration,2025-10-29,Villa,Villa,Residential,Off-Plan,Dubai Investment Park Second,Binghatti Aquarise - TOWER D,...,Downtown Dubai,Business Bay Metro Station,Dubai Mall,4,0,144.00,2703000.0,18770.83,1550.01600,1743.852967
403137,1-102-2025-77597,Sales,Sell - Pre registration,2025-08-20,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,AURESTA TOWER,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.91,479771.0,15521.55,332.71524,1441.986847
403138,1-102-2025-116742,Sales,Sell - Pre registration,2025-11-17,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,AURESTA TOWER,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.52,740744.0,24270.77,328.51728,2254.809854
403139,1-102-2025-75031,Sales,Sell - Pre registration,2025-08-14,Unit,Flat,Residential,Off-Plan,Al Barsha South Fourth,AURESTA TOWER,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,30.91,495681.0,16036.29,332.71524,1489.805517
403141,1-102-2025-98637,Sales,Sell - Pre registration,2025-10-06,Unit,Flat,Residential,Off-Plan,Nad Hessa,BELLE VIE BY ZIMAYA,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,Studio,1,39.69,716151.0,18043.61,427.22316,1676.292549
403142,1-102-2025-99881,Sales,Sell - Pre registration,2025-10-07,Unit,Flat,Residential,Off-Plan,Nad Hessa,BELLE VIE BY ZIMAYA,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,2,1,119.85,1643500.0,13712.97,1290.06540,1273.966421
403144,1-102-2025-134864,Sales,Sell - Pre registration,2025-12-29,Unit,Flat,Residential,Off-Plan,Madinat Al Mataar,Golf Hills,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,1,1,63.19,1079888.0,17089.54,680.17716,1587.656957
403145,1-102-2026-959,Sales,Sell - Pre registration,2026-01-06,Unit,Flat,Residential,Off-Plan,Palm Deira,ELLINGTON SANDS I - TOWER B,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,1,1,74.70,2269828.0,30385.92,804.07080,2822.920569
403146,1-102-2025-125823,Sales,Sell - Pre registration,2025-12-10,Unit,Flat,Residential,Off-Plan,Palm Deira,ELLINGTON SANDS I - TOWER B,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,2,1,129.20,3901828.0,30199.91,1390.70880,2805.639829
403147,1-102-2025-129954,Sales,Sell - Pre registration,2025-12-18,Villa,Villa,Residential,Off-Plan,Dubai Investment Park Second,ELLINGTON SANDS I - TOWER B,...,Sports City Swimming Academy,Dubai Internet City,Mall of the Emirates,3,0,148.78,3614888.0,24296.87,1601.46792,2257.234101

In [19]:
df.to_csv("cleaned_transactions.csv",index=False)